[2025-04-20T21:24:27.771+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-20T21:24:27.787+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline.db_view_operations.create_dashboard_summary_stats_view manual__2025-04-20T21:23:59.392682+00:00 [queued]>
[2025-04-20T21:24:27.794+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline.db_view_operations.create_dashboard_summary_stats_view manual__2025-04-20T21:23:59.392682+00:00 [queued]>
[2025-04-20T21:24:27.795+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-20T21:24:27.808+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): db_view_operations.create_dashboard_summary_stats_view> on 2025-04-20 21:23:59.392682+00:00
[2025-04-20T21:24:27.813+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'weather_data_pipeline', 'db_view_operations.create_dashboard_summary_stats_view', 'manual__2025-04-20T21:23:59.392682+00:00', '--job-id', '149', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmpqht0zjp7']
[2025-04-20T21:24:27.814+0000] {standard_task_runner.py:105} INFO - Job 149: Subtask db_view_operations.create_dashboard_summary_stats_view
[2025-04-20T21:24:27.815+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1568) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-20T21:24:27.816+0000] {standard_task_runner.py:72} INFO - Started process 1590 to run task
[2025-04-20T21:24:27.843+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_data_pipeline.db_view_operations.create_dashboard_summary_stats_view manual__2025-04-20T21:23:59.392682+00:00 [running]> on host 8e2c8626a9ef
[2025-04-20T21:24:27.898+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_data_pipeline' AIRFLOW_CTX_TASK_ID='db_view_operations.create_dashboard_summary_stats_view' AIRFLOW_CTX_EXECUTION_DATE='2025-04-20T21:23:59.392682+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-20T21:23:59.392682+00:00'
[2025-04-20T21:24:27.900+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-20T21:24:27.914+0000] {logging_mixin.py:190} INFO - Error executing SQL: list index out of range
[2025-04-20T21:24:27.914+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/operators/db_operations.py", line 57, in create_dashboard_summary_stats_view
    execute_sql_file(sql_file_path)
  File "/opt/airflow/dags/operators/db_operations.py", line 25, in execute_sql_file
    view_name = sql.split('VIEW')[1].split('AS')[0].strip()
                ~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
[2025-04-20T21:24:27.926+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_data_pipeline, task_id=db_view_operations.create_dashboard_summary_stats_view, run_id=manual__2025-04-20T21:23:59.392682+00:00, execution_date=20250420T212359, start_date=20250420T212427, end_date=20250420T212427
[2025-04-20T21:24:27.945+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-20T21:24:27.946+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 149 for task db_view_operations.create_dashboard_summary_stats_view (list index out of range; 1590)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/operators/db_operations.py", line 57, in create_dashboard_summary_stats_view
    execute_sql_file(sql_file_path)
  File "/opt/airflow/dags/operators/db_operations.py", line 25, in execute_sql_file
    view_name = sql.split('VIEW')[1].split('AS')[0].strip()
                ~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
[2025-04-20T21:24:27.989+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-20T21:24:28.006+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-20T21:24:28.008+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
