[2025-04-22T22:44:47.548+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline.ai_forecast_operations.forecast_co2_org1 manual__2025-04-22T22:44:12.596392+00:00 [queued]>
[2025-04-22T22:44:47.555+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline.ai_forecast_operations.forecast_co2_org1 manual__2025-04-22T22:44:12.596392+00:00 [queued]>
[2025-04-22T22:44:47.555+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-04-22T22:44:47.564+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): ai_forecast_operations.forecast_co2_org1> on 2025-04-22 22:44:12.596392+00:00
[2025-04-22T22:44:47.569+0000] {standard_task_runner.py:57} INFO - Started process 2965 to run task
[2025-04-22T22:44:47.571+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'weather_data_pipeline', 'ai_forecast_operations.forecast_co2_org1', 'manual__2025-04-22T22:44:12.596392+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmp0v3sdcfk']
[2025-04-22T22:44:47.572+0000] {standard_task_runner.py:85} INFO - Job 49: Subtask ai_forecast_operations.forecast_co2_org1
[2025-04-22T22:44:47.602+0000] {task_command.py:415} INFO - Running <TaskInstance: weather_data_pipeline.ai_forecast_operations.forecast_co2_org1 manual__2025-04-22T22:44:12.596392+00:00 [running]> on host ba2ad926eb92
[2025-04-22T22:44:47.655+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_data_pipeline' AIRFLOW_CTX_TASK_ID='ai_forecast_operations.forecast_co2_org1' AIRFLOW_CTX_EXECUTION_DATE='2025-04-22T22:44:12.596392+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-22T22:44:12.596392+00:00'
[2025-04-22T22:44:47.673+0000] {logging_mixin.py:151} INFO - DataFrame dtypes after processing: value    float64
dtype: object
[2025-04-22T22:44:47.673+0000] {logging_mixin.py:151} INFO - Not enough data for forecasting. Need at least 37 days, but got 1
[2025-04-22T22:44:47.674+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-04-22T22:44:47.680+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=weather_data_pipeline, task_id=ai_forecast_operations.forecast_co2_org1, execution_date=20250422T224412, start_date=20250422T224447, end_date=20250422T224447
[2025-04-22T22:44:47.704+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-04-22T22:44:47.718+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
